const CONFIG = {
    titleWeb: "Cậu nhớ trả lời thật nha",
    introTitle: 'Bạn Anne chăm học lười ăn',
    introDesc: `Cậu dễ bị ốm lắm đó, mỗi ngày cậu nhớ phải ăn đầy đủ đó nha. \n  Khi nào mà cậu mất ngủ,
    cậu cứ việc gọi tớ bất cứ thời gian nào cũng được, có khi tớ lại giúp cậu ngủ ngon đó 🤭`,
    btnIntro: 'Tớ nhớ ùiii',
    title: 'Anne nhớ không bao giờ được buồn một mình đâu nhaaa',
    desc: 'Vẫn có một người đang chờ nghe cậu tâm sự đó 🥰',
    btnYes: 'Chắc chắn rùiii <3',
    btnNo: 'Khum nha :3',
    question: 'Tại sao cậu lại chấp nhận tin nhắn của tớ zậy 😣\n (Tớ đọc được đóoo)',
    btnReply: 'Send',
    reply: 'Tại zì không yêu thì yêu mà không yêu thì yêu',
    mess: 'Á à hoá ra là zậy. Tớ biết rồi nhaaa 🙄',
    messDesc: 'Cậu được quyền chấp nhận tình cảm to bự của tớ 🤫\n (Ngày hết hạn: ∞)',
    btnAccept: 'Okiiiii lunnn',
}
